### PR TITLE
add checkup table

### LINKED ISSUE #19: Wrong grammar coded for karo1304

### PR DESCRIPTION
**Pull request by FredericBlum**
@MuffinLinwist Please report your check-up here.

We will also include #18 and #17 in this PR.

### CODE REVIEW

**Comment by FredericBlum** [comment]
@MuffinLinwist Do you have an overview of what the current state is? What issues are missing from being solved? I'd say we make a new release without the Karok data for now, so that at least the most recent version does not feature Karok.

**Comment by CMUgarte** [comment]
We do not have any other problems regarding a confusion of languages and/or sources, as it can be seen on [check/check_languages.csv](https://github.com/cldf-datasets/gata/blob/errata/check/check_languages.csv), @FredericBlum. 

We do have some problems regarding the paper publication (where Garrwa is written Garrrwa, and other mistakes with the reference's years). There is also another issue raised in #18, we are waiting for a response on how to treat the NA cases in our value table. Other than that, there aren't any more issues left. 

I can make a new release not including Karok's data, if everything else is fit on the dataset.

**Comment by FredericBlum** [comment]
@MuffinLinwist Please revert the changes you made to `values.csv` for the data from Bardi. Since we use the 1975 publication, we also have to make this the year of reference in the data values. Should be a quick Search&Replace.

**Comment by CMUgarte** [comment]
> @MuffinLinwist Please revert the changes you made to `values.csv` for the data from Bardi. Since we use the 1975 publication, we also have to make this the year of reference in the data values. Should be a quick Search&Replace.

I got that we used the 1972 publication. I'll uniformize the dataset according to this. Are you sure we used the 1975 publication?

**Comment by FredericBlum** [comment]
Not a 100% sure, but since everything pointed towards the 1975 publication, I think that's the most likely. Do you know who coded this languages? It's important that we are consistent with this annotation.

With respect to the "checks" folder: I wouldn't add this, since the main folders are quite systematic across datasets. I'd propose to keep it within `raw/others/`.

**Comment by CMUgarte** [comment]
It was @BadBatched, I'll ask him to confirm. From what I saw from the PDFs, it was the phd thesis published on 1972.

**Comment by FredericBlum** [comment]
Then of course we would have to adapt the source accordingly. But yes, confirming with @BadBatched before that is good.

**Comment by CMUgarte** [comment]
I just modified it and asked Adriano whether it was the same PDF he used. I'll hold to push the commit after he confirm me this.

**Comment by CMUgarte** [comment]
@FredericBlum, @BadBatched already confirmed to me that the `1975 edition` is the correct one. The last version of the converted dataset to CLDF already fix this. If everything is fit, we can go ahead and merge this PR.

**Review by FredericBlum — COMMENTED** [review]
There's still two problems:

a) Please make a clean change to raw/gata_raw.csv, so that it is easily readable to see what has been changed. Currently, the whole file is re-written, which is not optimal. We want to be able to track the changes. Please revert the changes to this file and re-do the changes
b) The Karok data is not yet excluded, please do so in all relevant files

**Comment by FredericBlum** [comment]
There is many commit oushes flying in that are probably not necessary. If you read my comment carefully, I am explicit about reverting the changes only for one file! Not for the others.

Please check out the answers in the following stackoverflow topic. https://stackoverflow.com/a/51755933

**Comment by CMUgarte** [comment]
@FredericBlum, this version of the dataset excludes Karok's data and redoes all of the changes of the `raw-data` for transparency with the history of the file.

**Comment by FredericBlum** [comment]
For learning purposes: If you go to FILES CHANGED, do the changes to the raw-data seem transparent to you?

Please go back to the commits you made and check which commit causes the problem. I will then recommend a solution to the problem. No further changes until then please.

**Comment by CMUgarte** [comment]
This is what happens when I renumber the entries. I did all of the other changes one by one on PyCharm and everything fine until this point. I tried to do it automatically with a script but didn't manage to do it, then.

**Comment by FredericBlum** [comment]
Exactly. And well, there is no need to renumber the entries. We can make it explicit that we have removed data. So the best solution would be to revert this last commit. Please read up carefully on how to do this, so we get the explicit file history that we want.

**Comment by CMUgarte** [comment]
> Exactly. And well, there is no need to renumber the entries. We can make it explicit that we have removed data. So the best solution would be to revert this last commit. Please read up carefully on how to do this, so we get the explicit file history that we want.

Thanks for giving me directions to the solution of this. I've modified the PR accordingly and the changes on the `raw data file` can now be seen in a transparent manner.

**Comment by FredericBlum** [comment]
Thanks, this looks much better now. Only one error missing: In line 2499, the Source and Year column got mixed up. Once you have fixed this, I will create the new release.

**Comment by CMUgarte** [comment]
Thanks for catching this. By now, everything should be fit and a new version of the dataset can be released.

**Pull request merged**
