### PR TITLE
adding the old categories for parameters

### PR DESCRIPTION
**Pull request by FredericBlum**
This PR restores the old categories and adds a script that is used for some overview plots.

@MuffinLinwist Could you double-check whether the new categories are correct?
@LinguList Is there a better place for the plots than /raw/scripts? We could create a new folder in the main directory instead.

### CODE REVIEW

**Comment by LinguList** [comment]
@Tarotis, yes, please make a folder `plots`, do not put any analyses into `raw`.

**Comment by LinguList** [comment]
@Tarotis, do you use a new, fresh virtual environment for this repository? I am asking since your requirements.txt changed, but you only applied the makecldf script. There are no major changes, but I am curious now.

**Comment by CMUgarte** [comment]
@Tarotis already checked. Everything is in order.

**Comment by LinguList** [comment]
@tarotis, it seems like using cldfviz would also be useful for this map. I do not know which parameters you want to plot there, but cldfviz may be useful to learn for you guys anyway. Check here: https://github.com/cldf/cldfviz

Examples are also in https://github.com/lexibank/lexibank-analysed/

There, check for the folder "plots".

**Comment by FredericBlum** [comment]
I did use a fresh venv, but I made another mistake: I follwed an old workflow that installed packages using `pip install -e ./`. However, since the requirements have been moved to the cldf-directory, pyglottolog etc did not get installed. Then, I followed the prompt that I had to install pyglottolog/concepticon/clts and did so manually, resulting in the mismatches in the package versions. Now I used `pip install -r cldf/requirements.txt` in order to not change the requirements. The file still appears as if it were changed though, and I am not sure why.

**Comment by LinguList** [comment]
If all works on your side, this is fine. Just wanted to check, as these 
cases jumped into my eye.

**Comment by FredericBlum** [comment]
@MuffinLinwist Could you double-check if my changes are ok, so we can merge this PR?

**Comment by CMUgarte** [comment]
@Tarotis, it seems that everything is perfect so I'm merging this PR.

**Pull request merged**
